python3 train_jumbot.py UOT --gpu_id [0] --lr 0.001 --alpha 0.01 --lambda_reg 0.5 --net ResNet50 --dset office-home --test_interval 2000 --s_dset_path ./data/office-home/Art.txt --t_dset_path ./data/office-home/Clipart.txt --batch_size 65 --output_dir "A_C" --ktype imq_v2 --khp 0.1 --lda 100 --out_file res_Nov10
python3 train_jumbot.py UOT --gpu_id [0] --lr 0.001 --alpha 0.01 --lambda_reg 0.5 --net ResNet50 --dset office-home --test_interval 2000 --s_dset_path ./data/office-home/Art.txt --t_dset_path ./data/office-home/Product.txt --batch_size 65 --output_dir "A_P" --ktype imq_v2 --khp 0.1 --lda 100 --out_file res_Nov10
python3 train_jumbot.py UOT --gpu_id [0] --lr 0.001 --alpha 0.01 --lambda_reg 0.5 --net ResNet50 --dset office-home --test_interval 2000 --s_dset_path ./data/office-home/Art.txt --t_dset_path ./data/office-home/Real_World.txt --batch_size 65 --output_dir "A_R" --ktype imq_v2 --khp 0.1 --lda 100 --out_file res_Nov10

python3 train_jumbot.py UOT --gpu_id [0] --lr 0.001 --alpha 0.01 --lambda_reg 0.5 --net ResNet50 --dset office-home --test_interval 2000 --s_dset_path ./data/office-home/Clipart.txt --t_dset_path ./data/office-home/Art.txt --batch_size 65 --output_dir "C_A" --ktype imq_v2 --khp 0.1 --lda 100 --out_file res_Nov10
python3 train_jumbot.py UOT --gpu_id [0] --lr 0.001 --alpha 0.01 --lambda_reg 0.5 --net ResNet50 --dset office-home --test_interval 2000 --s_dset_path ./data/office-home/Clipart.txt --t_dset_path ./data/office-home/Product.txt --batch_size 65 --output_dir "C_P" --ktype imq_v2 --khp 0.1 --lda 100 --out_file res_Nov10
python3 train_jumbot.py UOT --gpu_id [0] --lr 0.001 --alpha 0.01 --lambda_reg 0.5 --net ResNet50 --dset office-home --test_interval 2000 --s_dset_path ./data/office-home/Clipart.txt --t_dset_path ./data/office-home/Real_World.txt --batch_size 65 --output_dir "C_R" --ktype imq_v2 --khp 0.1 --lda 100 --out_file res_Nov10

python3 train_jumbot.py UOT --gpu_id [0] --lr 0.001 --alpha 0.01 --lambda_reg 0.5 --net ResNet50 --dset office-home --test_interval 2000 --s_dset_path ./data/office-home/Product.txt --t_dset_path ./data/office-home/Art.txt --batch_size 65 --output_dir "P_A" --ktype imq_v2 --khp 0.1 --lda 100 --out_file res_Nov10
python3 train_jumbot.py UOT --gpu_id [0] --lr 0.001 --alpha 0.01 --lambda_reg 0.5 --net ResNet50 --dset office-home --test_interval 2000 --s_dset_path ./data/office-home/Product.txt --t_dset_path ./data/office-home/Clipart.txt --batch_size 65 --output_dir "P_C" --ktype imq_v2 --khp 0.1 --lda 100 --out_file res_Nov10
python3 train_jumbot.py UOT --gpu_id [0] --lr 0.001 --alpha 0.01 --lambda_reg 0.5 --net ResNet50 --dset office-home --test_interval 2000 --s_dset_path ./data/office-home/Product.txt --t_dset_path ./data/office-home/Real_World.txt --batch_size 65 --output_dir "P_R" --ktype imq_v2 --khp 0.1 --lda 100 --out_file res_Nov10

python3 train_jumbot.py UOT --gpu_id [0] --lr 0.001 --alpha 0.01 --lambda_reg 0.5 --net ResNet50 --dset office-home --test_interval 2000 --s_dset_path ./data/office-home/Real_World.txt --t_dset_path ./data/office-home/Art.txt --batch_size 65 --output_dir "R_A" --ktype imq_v2 --khp 0.1 --lda 100 --out_file res_Nov10
python3 train_jumbot.py UOT --gpu_id [0] --lr 0.001 --alpha 0.01 --lambda_reg 0.5 --net ResNet50 --dset office-home --test_interval 2000 --s_dset_path ./data/office-home/Real_World.txt --t_dset_path ./data/office-home/Product.txt --batch_size 65 --output_dir "R_P" --ktype imq_v2 --khp 0.1 --lda 100 --out_file res_Nov10
python3 train_jumbot.py UOT --gpu_id [0] --lr 0.001 --alpha 0.01 --lambda_reg 0.5 --net ResNet50 --dset office-home --test_interval 2000 --s_dset_path ./data/office-home/Real_World.txt --t_dset_path ./data/office-home/Clipart.txt --batch_size 65 --output_dir "R_C" --ktype imq_v2 --khp 0.1 --lda 100 --out_file res_Nov10